sudo: false
language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    packages:
      - libcunit1-dev


script:
    - cd build/
    - make verbose=1 && ./cvector
    - grep FAILED CUnitAutomated-Results.xml | xargs -I {} [ "{}" = "<FAILED> 0 </FAILED> " ]

